import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiClient, getApiErrorMessage } from '../../api/client';
type Overview={checked_at:string;counts:Record<string,number>;tasks:Record<string,number>;accounts:Record<string,number>;operations:Record<string,number>;tribute_events:Record<string,number>;integrations:Record<string,boolean>;notes:string[]};
const panel='rounded-2xl border border-[var(--workspace-border)] bg-[var(--workspace-panel)] p-5';
const labels:Record<string,string>={users:'Пользователи',active_subscriptions:'Активные подписки',registered_7d:'Регистрации за 7 дней',with_project:'Создали проект',with_publication:'Опубликовали пост',projects:'Проекты',accounts:'Аккаунты',draft:'Черновики',queued:'В очереди',running:'В работе',success:'Выполнено',partial_success:'Частично выполнено',failed:'Ошибки',cancelled:'Отменено',active:'Активные',disabled:'Отключены',error:'Ошибка',warming_up:'Подготовка',cookies_expired:'Вход истёк',blocked:'Ограничение',proxy_error:'Ошибка прокси',pending:'Ожидает',applied:'Обработано',obsolete:'Устарело',unknown_tariff:'Неизвестный тариф'};
export default function AdminDashboardPage(){
 const [data,setData]=useState<Overview|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{setData((await apiClient.get<Overview>('/api/v1/admin/overview')).data);}catch(e){setError(getApiErrorMessage(e,'Не удалось загрузить дашборд.'));}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 return <section className='workspace-page space-y-5'><header className='flex flex-wrap justify-between gap-3'><div><h1 className='text-3xl font-semibold'>Дашборд администратора</h1><p className='mt-2 text-[var(--workspace-muted)]'>Клиенты, первые результаты и состояние сервиса в одном месте.</p></div><button disabled={busy} onClick={()=>void load()} className='rounded-full border border-[var(--workspace-border)] px-5 py-2 disabled:opacity-40'>{busy?'Обновляем…':'Обновить'}</button></header>{error&&<p role='alert' className={panel}>{error}</p>}{data&&<><div className='grid gap-3 sm:grid-cols-2 xl:grid-cols-4'>{Object.entries(data.counts).map(([key,n])=><div key={key} className={panel}><p className='text-sm text-[var(--workspace-muted)]'>{labels[key]||key}</p><strong className='mt-2 block text-3xl'>{n}</strong></div>)}</div><div className='grid gap-4 sm:grid-cols-2'>{[['Задания',data.tasks],['Подключённые аккаунты',data.accounts],['Генерация и сбор данных',data.operations],['Уведомления Tribute',data.tribute_events]].map(([title,values])=><article key={String(title)} className={panel}><h2 className='mb-4 text-lg font-semibold'>{String(title)}</h2>{!Object.keys(values).length?<p className='text-sm text-[var(--workspace-muted)]'>Пока нет данных</p>:Object.entries(values).map(([key,n])=><div key={key} className='flex justify-between py-1 text-sm'><span>{labels[key]||key}</span><strong>{n}</strong></div>)}</article>)}</div><div className={`${panel} space-y-3`}><h2 className='text-lg font-semibold'>Что требует внимания</h2><p>Ошибки заданий: {data.tasks.failed||0}. Аккаунты с истёкшим входом: {data.accounts.cookies_expired||0}. Ограничения: {data.accounts.blocked||0}. Ошибки прокси: {data.accounts.proxy_error||0}.</p><p>Уведомления с неизвестным тарифом: {data.tribute_events.unknown_tariff||0}; ожидающие обработки: {data.tribute_events.pending||0}.</p><div className='flex flex-wrap gap-4 text-sm underline'><Link to='/app/admin/users'>Проверить пользователей</Link><Link to='/app/admin/proxies'>Открыть диагностику прокси</Link><Link to='/app/admin/retention'>Помочь начать работу</Link></div></div><div className={`${panel} text-sm text-[var(--workspace-muted)]`}><p>Telegram: {data.integrations.telegram_configured?'настроен':'не настроен'}. Ключ Tribute: {data.integrations.tribute_key_configured?'настроен':'не настроен'}.</p>{data.notes.map(n=><p className='mt-2' key={n}>{n}</p>)}<p className='mt-3'>Обновлено: {new Date(data.checked_at).toLocaleString('ru-RU')}</p></div></>}</section>;
}
