import { useEffect, useState } from 'react';
import { apiClient, getApiErrorMessage } from '../../api/client';
type User={id:number;telegram_id:number|null;username:string|null;first_name:string;created_at:string;active_subscription:boolean;plan:string;phase:string;expires_at:string|null;gift_expires_at:string|null;projects:number;accounts:number;marketing_consent:boolean;onboarding_consent:boolean};
type Response={total:number;offset:number;users:User[]};
const panel='rounded-2xl border border-[var(--workspace-border)] bg-[var(--workspace-panel)] p-5';
function date(value:string|null){return value?new Date(value).toLocaleDateString('ru-RU'):'—';}
export default function AdminUsersPage(){
 const [data,setData]=useState<Response|null>(null);const [input,setInput]=useState('');const [search,setSearch]=useState('');const [offset,setOffset]=useState(0);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [refresh,setRefresh]=useState(0);
 useEffect(()=>{let active=true;setBusy(true);setError('');void apiClient.get<Response>('/api/v1/admin/users',{params:{search,offset,limit:50}}).then(r=>{if(active)setData(r.data);}).catch(e=>{if(active)setError(getApiErrorMessage(e,'Не удалось загрузить пользователей.'));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[search,offset,refresh]);
 return <section className='workspace-page space-y-5'><header><h1 className='text-3xl font-semibold'>Пользователи и подписки</h1><p className='mt-3 text-[var(--workspace-muted)]'>Проверьте доступ клиента и этап, на котором он остановился.</p></header><form className='flex flex-wrap gap-3' onSubmit={e=>{e.preventDefault();setOffset(0);setSearch(input);setRefresh(n=>n+1);}}><input aria-label='Поиск пользователя' placeholder='Имя, Telegram-ник или Telegram ID' value={input} onChange={e=>setInput(e.target.value)} maxLength={120} className='min-w-0 flex-1 rounded-xl border border-[var(--workspace-border)] bg-[var(--workspace-input)] p-3'/><button disabled={busy} className='rounded-full border border-[var(--workspace-border)] px-6 disabled:opacity-40'>{busy?'Загрузка…':'Найти'}</button></form>{error&&<p role='alert' className={panel}>{error}</p>}{data&&<><p className='text-sm text-[var(--workspace-muted)]'>Найдено: {data.total}. Сведения доступны только владельцу.</p><div className='space-y-3'>{data.users.map(u=><article key={u.id} className={panel}><div className='flex flex-wrap justify-between gap-2'><div><h2 className='font-semibold'>{u.first_name} {u.username&&<span className='font-normal text-[var(--workspace-muted)]'>@{u.username}</span>}</h2><p className='mt-1 text-xs text-[var(--workspace-muted)]'>Клиент #{u.id} · Telegram {u.telegram_id||'—'} · регистрация {date(u.created_at)}</p></div><strong className='text-sm'>{u.active_subscription?'Доступ активен':'Доступ неактивен'}</strong></div><div className='mt-4 grid gap-2 text-sm sm:grid-cols-2'><p>Тариф: {u.plan||'—'} · {u.phase==='cancelled'?'Продление отменено':u.phase==='paid'?'Оплачено':u.phase==='trial'?'Пробный период':u.phase==='gift'?'Подарок':u.phase==='none'?'Нет оплаченного периода':u.phase}</p><p>Оплаченный срок до: {date(u.expires_at)} · подарок до: {date(u.gift_expires_at)}</p><p>Проекты: {u.projects} · аккаунты: {u.accounts}</p><p>Сообщения: помощь {u.onboarding_consent?'разрешена':'отключена'}, новости {u.marketing_consent?'разрешены':'отключены'}</p></div></article>)}</div>{!data.users.length&&<p className={panel}>Пользователи не найдены</p>}<div className='flex gap-3'><button disabled={busy||offset===0} onClick={()=>setOffset(n=>Math.max(0,n-50))} className='rounded-full border px-5 py-2 disabled:opacity-40'>Назад</button><button disabled={busy||offset+50>=data.total} onClick={()=>setOffset(n=>n+50)} className='rounded-full border px-5 py-2 disabled:opacity-40'>Далее</button></div></>}</section>;
}
