import { useEffect, useMemo, useState } from "react";
import { apiClient, getApiErrorMessage } from "../../api/client";

type Campaign = { id: number; title: string; message: string; segment: string; kind: string; status: string; recipient_count: number; created_at: string; delivery_stats: Record<string, number> };
type Dashboard = { sending_enabled: boolean; automated_enabled: boolean; counts: { users: number; opted_in: number; reachable: number; queued: number; sent: number; failed: number; uncertain: number }; campaigns: Campaign[]; automatic_rules: { key: string; days: number; message: string }[] };
type Preview = { eligible_count: number; excluded_count: number };
const segments: Record<string, string> = { all: "Все пользователи", no_project: "Ещё не создали проект", no_first_post: "Ещё не опубликовали первый пост", active_subscribers: "С активной подпиской" };
const statuses: Record<string, string> = { queued: "В очереди", pending: "В очереди", sending: "Отправляется", sent: "Отправлено", completed: "Завершена", cancelled: "Отменена", failed: "Ошибка", uncertain: "Результат неизвестен", skipped: "Пропущено", draft: "Черновик" };
const panel = "rounded-2xl border border-[var(--workspace-border)] bg-[var(--workspace-panel)] p-5 sm:p-6";
const control = "mt-2 w-full rounded-xl border border-[var(--workspace-border)] bg-[var(--workspace-input)] p-3 text-[var(--workspace-ink)]";
const button = "rounded-full border border-[var(--workspace-border)] px-5 py-2.5 text-sm font-medium disabled:opacity-40";

export default function RetentionAdminPage() {
  const [data, setData] = useState<Dashboard | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const [title, setTitle] = useState("");
  const [message, setMessage] = useState("");
  const [segment, setSegment] = useState("no_project");
  const [kind, setKind] = useState("onboarding");
  const [preview, setPreview] = useState<Preview | null>(null);
  const requestKey = useMemo(() => crypto.randomUUID(), [title, message, segment, kind]);
  async function load() { const result = await apiClient.get<Dashboard>("/api/v1/admin/retention"); setData(result.data); }
  useEffect(() => { void load().catch(e => setError(getApiErrorMessage(e, "Доступ разрешён только владельцу сервиса."))); }, []);
  useEffect(() => { setPreview(null); }, [message, segment, kind]);
  async function action(fn: () => Promise<unknown>, success?: string) {
    setBusy(true); setError(""); setNotice("");
    try { await fn(); if (success) setNotice(success); await load(); }
    catch (e) { setError(getApiErrorMessage(e, "Не удалось выполнить действие.")); }
    finally { setBusy(false); }
  }
  async function settings(sending: boolean, automated: boolean) {
    await action(() => apiClient.put("/api/v1/admin/retention/settings", { sending_enabled: sending, automated_enabled: automated }), "Настройки отправки сохранены.");
  }
  return <section className="workspace-page space-y-5">
    <header><p className="text-sm text-[var(--workspace-muted)]">Только для владельца</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Рассылки и помощь со стартом</h1><p className="mt-3 max-w-2xl text-[var(--workspace-muted)]">Поддержите тех, кто остановился на первом шаге. Каждая рассылка учитывает согласие пользователя и доступность Telegram-бота.</p></header>
    {error && <p className={panel} role="alert">{error}</p>}{notice && <p className={panel} role="status">{notice}</p>}
    {!data ? !error && <p>Загружаем данные…</p> : <>
      <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Пользователи", data.counts.users], ["Дали согласие", data.counts.opted_in], ["Бот доступен", data.counts.reachable], ["В очереди", data.counts.queued], ["Отправлено", data.counts.sent], ["Ошибки", data.counts.failed]].map(([label, count]) => <div key={label} className={panel}><p className="text-xs text-[var(--workspace-muted)]">{label}</p><strong className="mt-2 block text-2xl">{count}</strong></div>)}</div>
      <div className={`${panel} space-y-4`}><h2 className="text-xl font-semibold">Управление отправкой</h2><p className="text-sm text-[var(--workspace-muted)]">Лимиты: не чаще одного сообщения за 72 часа, максимум 2 за неделю и 3 за месяц. Отправка с 10:00 до 20:00 по Москве. Неясный результат доставки не повторяем вслепую.</p>{data.counts.uncertain > 0 && <p role="status" className="text-sm">Не подтверждена доставка {data.counts.uncertain} сообщений. Они могли прийти пользователям; автоматических повторов не будет.</p>}<p className="text-sm text-[var(--workspace-muted)]">{data.sending_enabled ? "Отправка включена. Очередь обрабатывается фоновым заданием." : "Отправка выключена. Кампании можно подготовить, сообщения пользователям не уходят."}</p><div className="flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={() => { if (data.sending_enabled || window.confirm("Включить отправку? Подготовленные кампании в очереди начнут отправляться пользователям с согласием.")) void settings(!data.sending_enabled, data.automated_enabled); }}>{data.sending_enabled ? "Остановить отправку" : "Включить отправку"}</button><button className={button} disabled={busy} onClick={() => { if (data.automated_enabled || window.confirm("Включить автоматические подсказки? Сообщения получат только пользователи, разрешившие помощь со стартом.")) void settings(data.sending_enabled, !data.automated_enabled); }}>{data.automated_enabled ? "Выключить автоматические подсказки" : "Включить автоматические подсказки"}</button><button className={button} disabled={busy} onClick={() => void action(load)}>Обновить данные</button></div></div>
      <form className={`${panel} space-y-4`} onSubmit={e => { e.preventDefault(); if (!preview?.eligible_count) return; if (window.confirm(`Поставить рассылку «${title}» в очередь? Получателей сейчас: ${preview.eligible_count}. ${data.sending_enabled ? "Отправка включена." : "Отправка начнётся после включения."}`)) void action(async () => { await apiClient.post("/api/v1/admin/retention/campaigns", { title, message, segment, kind, request_key: requestKey }); setTitle(""); setMessage(""); setPreview(null); }, "Рассылка добавлена в очередь. Согласие и доступность бота будут повторно проверены перед отправкой."); }}>
        <h2 className="text-xl font-semibold">Новая рассылка</h2><label className="block text-sm">Название для вас<input required maxLength={120} value={title} disabled={busy} onChange={e => setTitle(e.target.value)} className={control} placeholder="Помочь создать первый проект" /></label>
        <div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm">Кому<select className={control} value={segment} disabled={busy} onChange={e => setSegment(e.target.value)}>{Object.entries(segments).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm">Тип согласия<select className={control} value={kind} disabled={busy} onChange={e => setKind(e.target.value)}><option value="onboarding">Помощь со стартом</option><option value="marketing">Новости и рекламные предложения</option></select></label></div>
        <label className="block text-sm">Сообщение в Telegram<textarea required maxLength={3500} rows={5} value={message} disabled={busy} onChange={e => setMessage(e.target.value)} className={control} placeholder="Привет! Если пока не удалось запустить первый проект, мы поможем разобраться. Напишите в поддержку @cuartenlol." /></label><p className="text-xs text-[var(--workspace-muted)]">Обычный текст без HTML. {message.length}/3500. Рекламные предложения выбирайте как «Новости».</p>
        <div className="rounded-2xl bg-[var(--workspace-soft)] p-4"><p className="mb-2 text-xs font-medium text-[var(--workspace-muted)]">Предпросмотр сообщения</p><p className="whitespace-pre-wrap break-words text-sm leading-6">{message || "Здесь появится ваш текст"}</p><p className="mt-4 text-xs text-[var(--workspace-muted)]">Отписка доступна в сообщении и настройках кабинета.</p></div>
        {preview && <p role="status" className="text-sm">Получателей: <strong>{preview.eligible_count}</strong>. Исключено: {preview.excluded_count} — другой этап работы, нет согласия, бот недоступен или достигнут лимит сообщений. Список может измениться до отправки.</p>}
        <div className="flex flex-wrap gap-3"><button type="button" className={button} disabled={busy || !message.trim()} onClick={() => void action(async () => { const result = await apiClient.post<Preview>("/api/v1/admin/retention/preview", { segment, kind, message }); setPreview(result.data); })}>Проверить получателей</button><button type="submit" className={`${button} bg-[var(--workspace-accent)] text-[var(--workspace-accent-ink)]`} disabled={busy || !title.trim() || !message.trim() || !preview?.eligible_count}>Добавить в очередь</button></div>
      </form>
      <div className={`${panel} space-y-4`}><h2 className="text-xl font-semibold">Автоматические подсказки</h2><p className="text-sm text-[var(--workspace-muted)]">{data.automated_enabled ? "Включены." : "Пока выключены."} Перед отправкой заново проверяем, остался ли человек на этом шаге. Выполненный шаг отменяет ненужную подсказку.</p>{data.automatic_rules.map(rule => <article key={rule.key} className="rounded-xl border border-[var(--workspace-border)] p-4"><h3 className="font-medium">Через {rule.days} дн. · {rule.key.startsWith("no_project") ? "проект ещё не создан" : rule.key.startsWith("no_first_post") ? "первый пост ещё не опубликован" : rule.key}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[var(--workspace-muted)]">{rule.message}</p></article>)}</div>
      <div className="space-y-3"><h2 className="text-xl font-semibold">Кампании</h2>{!data.campaigns.length && <p className={panel}>Рассылок пока нет. Начните с короткого сообщения, которое поможет выполнить один следующий шаг.</p>}{data.campaigns.map(campaign => <article key={campaign.id} className={`${panel} space-y-3`}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{campaign.title}</h3><span className="text-sm">{statuses[campaign.status] || campaign.status}</span></div><p className="text-xs text-[var(--workspace-muted)]">{segments[campaign.segment] || campaign.segment} · {campaign.recipient_count} получателей · {new Date(campaign.created_at).toLocaleString("ru-RU")}</p><p className="text-xs text-[var(--workspace-muted)]">{Object.entries(campaign.delivery_stats || {}).map(([status, count]) => `${statuses[status] || status}: ${count}`).join(" · ")}</p><p className="whitespace-pre-wrap break-words text-sm leading-6">{campaign.message}</p>{["queued", "pending", "sending"].includes(campaign.status) && <button type="button" className={button} disabled={busy} onClick={() => void action(() => apiClient.post(`/api/v1/admin/retention/campaigns/${campaign.id}/cancel`), "Рассылка остановлена. Уже отправленные сообщения отозвать нельзя.")}>Остановить кампанию</button>}</article>)}</div>
    </>}
  </section>;
}
