export const seoLandingRoutePaths = [
  "/threads-autoposting/",
  "/threads-post-generator/",
  "/threads-ideas-generator/",
  "/threads-content-plan/",
  "/threads-trends/",
  "/threads-scheduler/",
  "/threads-hook-analyzer/",
  "/personal-brand-strategy-generator/",
  "/personal-brand/",
  "/personal-brand-for-experts/",
  "/for-smm/",
  "/for-marketers/",
  "/for-agencies/",
  "/for-psychologists/",
  "/for-lawyers/",
  "/for-photographers/",
  "/for-consultants/",
  "/blog/",
  "/research/",
  "/compare/",
] as const;
