"""init

Revision ID: 53d2dbc9b349
Revises: 
Create Date: 2026-05-20 17:37:21.774050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d2dbc9b349'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_type', sa.Enum('virality', 'hook', 'formatting', 'retention', 'project_context', 'tone_of_voice', name='prompttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_prompts_id'), 'global_prompts', ['id'], unique=False)
    op.create_index('ix_global_prompts_type_active', 'global_prompts', ['prompt_type', 'is_active'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('niche', sa.String(length=255), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('tone_of_voice', sa.Text(), nullable=True),
    sa.Column('product_context', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('twitter', 'instagram', 'facebook', 'threads', 'bluesky', name='platform'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('proxy_url', sa.String(length=1024), nullable=True),
    sa.Column('session_data_encrypted', sa.Text(), nullable=True),
    sa.Column('cookies_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', 'error', 'warming_up', name='accountstatus'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index('ix_accounts_project_platform', 'accounts', ['project_id', 'platform'], unique=False)
    op.create_table('project_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('prompt_type', sa.Enum('virality', 'hook', 'formatting', 'retention', 'project_context', 'tone_of_voice', name='prompttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_prompts_id'), 'project_prompts', ['id'], unique=False)
    op.create_index('ix_project_prompts_project_type', 'project_prompts', ['project_id', 'prompt_type'], unique=False)
    op.create_table('saved_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('twitter', 'instagram', 'facebook', 'threads', 'bluesky', name='platform'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('author_handle', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('virality_score', sa.Float(), nullable=True),
    sa.Column('hook_analysis', sa.Text(), nullable=True),
    sa.Column('adaptation_notes', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_trends_id'), 'saved_trends', ['id'], unique=False)
    op.create_index('ix_saved_trends_project_platform', 'saved_trends', ['project_id', 'platform'], unique=False)
    op.create_table('posting_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('source_trend_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('twitter', 'instagram', 'facebook', 'threads', 'bluesky', name='platform'), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('draft', 'queued', 'running', 'success', 'failed', 'cancelled', name='postingtaskstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('external_post_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_trend_id'], ['saved_trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posting_tasks_id'), 'posting_tasks', ['id'], unique=False)
    op.create_index('ix_posting_tasks_project_status', 'posting_tasks', ['project_id', 'status'], unique=False)
    op.create_index('ix_posting_tasks_scheduled_at', 'posting_tasks', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posting_tasks_scheduled_at', table_name='posting_tasks')
    op.drop_index('ix_posting_tasks_project_status', table_name='posting_tasks')
    op.drop_index(op.f('ix_posting_tasks_id'), table_name='posting_tasks')
    op.drop_table('posting_tasks')
    op.drop_index('ix_saved_trends_project_platform', table_name='saved_trends')
    op.drop_index(op.f('ix_saved_trends_id'), table_name='saved_trends')
    op.drop_table('saved_trends')
    op.drop_index('ix_project_prompts_project_type', table_name='project_prompts')
    op.drop_index(op.f('ix_project_prompts_id'), table_name='project_prompts')
    op.drop_table('project_prompts')
    op.drop_index('ix_accounts_project_platform', table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_global_prompts_type_active', table_name='global_prompts')
    op.drop_index(op.f('ix_global_prompts_id'), table_name='global_prompts')
    op.drop_table('global_prompts')
    # ### end Alembic commands ###
